name: 🚀 Deploy Laravel Project via FTP

on:
  push:
    branches:
      - main  # main branch push edilince çalışacak

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.ankaratadilatdekorasyon.com.tr
          username: ankaratadilatdek
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /home/ankaratadilatdek/hts.ankaratadilatdekorasyon.com.tr/
          local-dir: ./  # tüm proje yüklenecek
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/storage/**
            **/.env
            **/tests/**
            **/README.md
