# GitHub Action Adı
name: Deploy Laravel Project to FTP

# Tetikleyici: 'main' branch'ine her push yapıldığında çalışır
on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
    
    # 1. Adım: Kodu (repository) checkout et
    - name: Check out repository
      uses: actions/checkout@v4

    # 2. Adım: PHP Ortamını Kur
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, xml, ctype, json, tokenizer, dom, pdo, pdo_mysql
        tools: composer

    # 3. Adım: Composer bağımlılıklarını kur (vendor klasörünü oluşturur)
    - name: Install Composer Dependencies
      run: composer install --no-interaction --no-dev --optimize-autoloader

    # 4. YENİ ADIM: Node.js (NPM için) Ortamını Kur
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Güncel LTS sürümü
        cache: 'npm' # NPM paketlerini hız için cache'le

    # 5. YENİ ADIM: NPM bağımlılıklarını kur (node_modules oluşturur)
    - name: Install NPM Dependencies
      run: npm install

    # 6. YENİ ADIM: CSS/JS dosyalarını derle (public/build klasörünü oluşturur)
    - name: Build Assets (Vite)
      run: npm run build

    # 7. Adım: Laravel Optimizasyonu (Eski Adım 4)
    # (npm run build'den sonra çalışması daha güvenli)
    - name: Run Laravel Optimize Commands
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache
        php artisan event:cache

    # 8. Adım: FTP ile Sunucuya Yükle (Eski Adım 5)
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.SERVER_PATH }}
        protocol: ftp
        port: 21
        timeout: 30000
        
        # Hariç tutulacak dosyalar (ÇOK ÖNEMLİ)
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .env
          .env.example
          .github/**
          storage/framework/sessions/*
          storage/framework/views/*
          storage/framework/cache/data/*
          storage/logs/*
          public/storage
          
          # Docker ve Sail dosyaları (sunucuya gitmesine gerek yok)
          docker-compose.yml
          .dockerignore
          *.md
          *.sqlite
